/**
 * Playwright API test templates.
 *
 * Each template function returns a ready-to-use `.spec.ts` string that:
 *  - Uses the `request` fixture from `@playwright/test` (NO page/browser).
 *  - Asserts `response.ok()` and validates basic body shape.
 *  - Includes Given/When/Then comments for traceability.
 *  - Uses {{PLACEHOLDER}} variables that Claude fills in before calling write_file.
 *  - Is valid TypeScript that compiles with strict mode.
 *
 * Convention: method names match the HTTP verb or "error" for 4xx scenarios.
 */

export type TemplateMethod = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'error' | 'screenshot';

/**
 * Returns the list of placeholder variables present in a template string.
 * Variables follow the pattern {{VARIABLE_NAME}}.
 */
export function extractVariables(template: string): string[] {
  const matches = template.matchAll(/\{\{([A-Z0-9_]+)\}\}/g);
  const unique = new Set<string>();
  for (const match of matches) {
    unique.add(`{{${match[1]}}}`);
  }
  return Array.from(unique);
}

/**
 * Returns a Playwright API spec template for the given HTTP method or error scenario.
 * All templates use the `request` fixture exclusively — no selectors, no page.
 */
export function getTemplate(method: TemplateMethod): string {
  switch (method) {
    case 'GET':
      return getTemplateGET();
    case 'POST':
      return getTemplatePOST();
    case 'PUT':
      return getTemplatePUT();
    case 'DELETE':
      return getTemplateDELETE();
    case 'error':
      return getTemplateError();
    case 'screenshot':
      return getTemplateScreenshot();
  }
}

// ---------------------------------------------------------------------------
// GET template
// ---------------------------------------------------------------------------

function getTemplateGET(): string {
  return `import { test, expect } from '@playwright/test';

/**
 * API test: GET {{ENDPOINT}}
 * Generated by QAcito — fill in {{PLACEHOLDER}} variables before running.
 */
test.describe('GET {{ENDPOINT}}', () => {
  // Given: a running API server accessible at BASE_URL
  // When:  a GET request is sent to ENDPOINT (with optional auth)
  // Then:  the response is successful and the body has the expected shape

  test('returns {{EXPECTED_STATUS}} with valid body', async ({ request }) => {
    // Given
    const url = \`{{BASE_URL}}{{ENDPOINT}}\`;

    // When
    const response = await request.get(url, {
      headers: {
        Authorization: 'Bearer {{AUTH_TOKEN}}',
      },
    });

    // Then
    expect(response.status()).toBe({{EXPECTED_STATUS}});
    expect(response.ok()).toBeTruthy();

    const body = await response.json();
    expect(body).toBeDefined();
    // TODO: assert specific fields, e.g. expect(body.id).toBeDefined();
  });
});
`;
}

// ---------------------------------------------------------------------------
// POST template
// ---------------------------------------------------------------------------

function getTemplatePOST(): string {
  return `import { test, expect } from '@playwright/test';

/**
 * API test: POST {{ENDPOINT}}
 * Generated by QAcito — fill in {{PLACEHOLDER}} variables before running.
 */
test.describe('POST {{ENDPOINT}}', () => {
  // Given: a running API server and a valid request body
  // When:  a POST request is sent with JSON data
  // Then:  the response confirms creation/processing and returns the resource

  test('creates resource and returns {{EXPECTED_STATUS}}', async ({ request }) => {
    // Given
    const url = \`{{BASE_URL}}{{ENDPOINT}}\`;
    const payload = {
      // TODO: replace with actual request body fields
      name: '{{RESOURCE_NAME}}',
    };

    // When
    const response = await request.post(url, {
      headers: {
        Authorization: 'Bearer {{AUTH_TOKEN}}',
        'Content-Type': 'application/json',
      },
      data: payload,
    });

    // Then
    expect(response.status()).toBe({{EXPECTED_STATUS}});
    expect(response.ok()).toBeTruthy();

    const body = await response.json();
    expect(body).toBeDefined();
    // TODO: assert created resource fields, e.g. expect(body.id).toBeDefined();
  });
});
`;
}

// ---------------------------------------------------------------------------
// PUT template
// ---------------------------------------------------------------------------

function getTemplatePUT(): string {
  return `import { test, expect } from '@playwright/test';

/**
 * API test: PUT {{ENDPOINT}}
 * Generated by QAcito — fill in {{PLACEHOLDER}} variables before running.
 */
test.describe('PUT {{ENDPOINT}}', () => {
  // Given: an existing resource identified by RESOURCE_ID
  // When:  a PUT request is sent with the updated payload
  // Then:  the response confirms the update with the expected status

  test('updates resource and returns {{EXPECTED_STATUS}}', async ({ request }) => {
    // Given
    const url = \`{{BASE_URL}}{{ENDPOINT}}/{{RESOURCE_ID}}\`;
    const payload = {
      // TODO: replace with actual fields to update
      name: '{{UPDATED_NAME}}',
    };

    // When
    const response = await request.put(url, {
      headers: {
        Authorization: 'Bearer {{AUTH_TOKEN}}',
        'Content-Type': 'application/json',
      },
      data: payload,
    });

    // Then
    expect(response.status()).toBe({{EXPECTED_STATUS}});
    expect(response.ok()).toBeTruthy();

    const body = await response.json();
    expect(body).toBeDefined();
    // TODO: assert updated fields, e.g. expect(body.name).toBe(payload.name);
  });
});
`;
}

// ---------------------------------------------------------------------------
// DELETE template
// ---------------------------------------------------------------------------

function getTemplateDELETE(): string {
  return `import { test, expect } from '@playwright/test';

/**
 * API test: DELETE {{ENDPOINT}}
 * Generated by QAcito — fill in {{PLACEHOLDER}} variables before running.
 */
test.describe('DELETE {{ENDPOINT}}', () => {
  // Given: an existing resource identified by RESOURCE_ID
  // When:  a DELETE request is sent for that resource
  // Then:  the response confirms deletion and the resource no longer exists

  test('deletes resource and returns {{EXPECTED_STATUS}}', async ({ request }) => {
    // Given
    const url = \`{{BASE_URL}}{{ENDPOINT}}/{{RESOURCE_ID}}\`;

    // When
    const response = await request.delete(url, {
      headers: {
        Authorization: 'Bearer {{AUTH_TOKEN}}',
      },
    });

    // Then
    expect(response.status()).toBe({{EXPECTED_STATUS}});
    // DELETE responses are often 204 No Content — only assert body if present
    if ({{EXPECTED_STATUS}} !== 204) {
      expect(response.ok()).toBeTruthy();
      const body = await response.json();
      expect(body).toBeDefined();
    }
  });
});
`;
}

// ---------------------------------------------------------------------------
// Error (4xx) template
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Screenshot (visual regression) template
// ---------------------------------------------------------------------------

function getTemplateScreenshot(): string {
  return `import { test, expect } from '@playwright/test';

/**
 * Visual regression test: {{ENDPOINT}}
 * Generated by QAcito. Fill in {{PLACEHOLDER}} variables before running.
 * Run with --update-snapshots to regenerate baselines after intentional UI changes.
 */
test.describe('{{ENDPOINT}} — visual regression', () => {
  test('matches visual baseline', async ({ page }) => {
    await page.goto(\`{{BASE_URL}}{{ENDPOINT}}\`);
    await page.waitForLoadState('networkidle');
    await expect(page).toHaveScreenshot('{{SNAPSHOT_NAME}}.png', {
      maxDiffPixelRatio: 0.02,
    });
  });
});
`;
}

// ---------------------------------------------------------------------------
// Error (4xx) template
// ---------------------------------------------------------------------------

function getTemplateError(): string {
  return `import { test, expect } from '@playwright/test';

/**
 * API test: error scenario for {{ENDPOINT}}
 * Generated by QAcito — fill in {{PLACEHOLDER}} variables before running.
 */
test.describe('{{ENDPOINT}} — error handling', () => {
  // Given: an API endpoint that validates input
  // When:  an invalid or unauthorised request is sent
  // Then:  the response returns the expected error status and error message

  test('returns {{EXPECTED_STATUS}} for invalid input', async ({ request }) => {
    // Given
    const url = \`{{BASE_URL}}{{ENDPOINT}}\`;
    const invalidPayload = {
      // TODO: replace with a payload that triggers the error
      {{INVALID_FIELD}}: null,
    };

    // When
    const response = await request.post(url, {
      headers: {
        Authorization: 'Bearer {{AUTH_TOKEN}}',
        'Content-Type': 'application/json',
      },
      data: invalidPayload,
    });

    // Then — status must be the expected error code (e.g. 400, 401, 404, 422)
    expect(response.status()).toBe({{EXPECTED_STATUS}});
    expect(response.ok()).toBeFalsy();

    const body = await response.json();
    expect(body).toBeDefined();
    // TODO: assert error message shape, e.g.:
    // expect(body.error).toBeDefined();
    // expect(typeof body.message).toBe('string');
  });
});
`;
}
